"""UI integration for FusionServe.

This module wires the React SPA built under ``ui/`` into the Litestar
application using Litestar's first-party static-files router. Two
artefacts are exported:

- :class:`RedirectRenderPlugin` — a custom
  :class:`~litestar.openapi.plugins.OpenAPIRenderPlugin` registered as
  the default plugin on the OpenAPI router. The upstream OpenAPI plugin
  auto-mounts the default plugin at the configured router root, so
  ``GET <base_path>/`` returns a 302 redirect to :attr:`Settings.ui_path`
  (default ``/api/-/``) where the SPA is mounted. Sibling render plugins
  (``SwaggerRenderPlugin``, ``ScalarRenderPlugin``) coexist normally at
  ``<base_path>/swagger`` and ``<base_path>/scalar``.
- :func:`build_spa_route_handler` — returns the
  :class:`~litestar.router.Router` mounted at :attr:`Settings.ui_path`
  with ``html_mode=True``. It serves both ``index.html`` (at the mount
  root and as a fallback for unmatched paths) and the hashed JS/CSS
  chunks Vite emits, all from the bundle directory
  ``src/fusionserve/web/dist`` (shipped inside the Python wheel).
  Because Vite is configured to emit *relative* asset URLs
  (``./assets/...`` in ``index.html``), the chunks resolve against
  ``<ui_path>/assets/...`` automatically — no separate asset prefix or
  second router is needed, and the SPA can be relocated by changing
  only :attr:`Settings.ui_path`.

The router carries ``opt={"exclude_from_auth": True}`` so the
authentication middleware (which honours that key via
:attr:`~litestar.middleware.AbstractAuthenticationMiddleware.exclude_opt_key`)
skips static assets without needing routes added to its URL-pattern
exclude list. The dev workflow is fully out-of-process: developers run
``pnpm run dev`` in ``ui/`` and the Vite dev server proxies ``/api``
to the Litestar backend. The Python side only serves the prebuilt SPA
from ``src/fusionserve/web/dist`` (regenerated by ``pnpm run build``).

Path / routing notes:

- The default :attr:`Settings.ui_path` (``/api/-/``) lives **inside**
  :attr:`Settings.base_path`. Litestar's path-converter matcher
  ``{path:str}`` matches a single segment without slashes, so the
  OpenAPI router's auto-registered ``<base_path>/{path:str}`` not-found
  handler does **not** shadow multi-segment paths like ``/api/-/...``;
  the SPA router's more-specific prefix wins.
- The trailing-slash form ``<ui_path>`` (e.g. ``/api/-/``) is canonical.
  The slashless ``<base_path>/-`` form is reachable by the OpenAPI
  not-found handler and will 404 — document the trailing slash to users
  (the ``/api/`` redirect emits it correctly).
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import Any

from litestar.connection import Request
from litestar.enums import MediaType, OpenAPIMediaType
from litestar.openapi.plugins import OpenAPIRenderPlugin
from litestar.response import Redirect
from litestar.router import Router
from litestar.static_files import create_static_files_router

from .config import settings

#: Repository / package layout, derived from this file's location.
#: Layout assumed: ``<repo>/src/fusionserve/ui.py``. Used to resolve
#: the bundled ``web/dist`` output directory.
_PACKAGE_DIR: Path = Path(__file__).resolve().parent

#: Where the production Vite build emits assets. Co-located with the
#: Python package so the wheel ships the built SPA without extra
#: packaging configuration.
_BUNDLE_DIR: Path = _PACKAGE_DIR / "web" / "dist"


class RedirectRenderPlugin(OpenAPIRenderPlugin):
    """OpenAPI render plugin that redirects to the React SPA.

    Registered as the first entry of
    :attr:`~litestar.openapi.OpenAPIConfig.render_plugins`, this plugin
    becomes the *default* plugin. Litestar's OpenAPI router auto-mounts
    the default plugin's handler at the router root (``settings.base_path``
    in our setup), so ``GET /api/`` returns a 302 redirect to
    :attr:`Settings.ui_path` — where the SPA static-files router serves
    ``index.html``. Users hitting the canonical API base URL land in the
    UI without having to know the SPA path.

    The plugin departs from the sibling render plugins
    (``JsonRenderPlugin``, ``SwaggerRenderPlugin``, …) in one important
    way: :meth:`render` returns a :class:`~litestar.response.Redirect`
    Response rather than ``bytes``. Litestar handles ``Response`` returns
    from handlers regardless of the declared return annotation, so the
    302 is served directly; the upstream ``-> bytes`` signature is kept
    only for API parity with the rest of the render-plugin family.
    """

    def __init__(
        self,
        *,
        path: str | Sequence[str] = "",
        media_type: MediaType | OpenAPIMediaType = MediaType.TEXT,
        **kwargs: Any,
    ) -> None:
        """Initialise the redirect plugin.

        Args:
            path: Path (relative to the OpenAPI router root) at which the
                redirect handler is registered. Defaults to ``""`` so the
                handler binds to the router root itself — the upstream
                OpenAPI plugin additionally promotes the default plugin's
                handler to ``"/"``, which together means ``/api`` and
                ``/api/`` both redirect.
            media_type: Required by the
                :class:`OpenAPIRenderPlugin` base class but practically
                ignored: the :class:`Redirect` Response sets its own
                ``Location`` header and ``302`` status independently of
                the declared media type.
            **kwargs: Forwarded to the base class for forward-compat with
                future :class:`OpenAPIRenderPlugin` parameters.
        """
        super().__init__(path=path, media_type=media_type, **kwargs)

    def render(self, request: Request, openapi_schema: dict[str, Any]) -> bytes:
        """Return a 302 redirect to :attr:`Settings.ui_path`.

        The return type annotation is ``bytes`` for parity with the
        :class:`OpenAPIRenderPlugin` contract, but the actual return
        value is a :class:`~litestar.response.Redirect` Response.
        Litestar's response cycle accepts any ``Response`` instance from
        a handler return — it short-circuits serialization and sends the
        response as-is — so the upstream ``-> bytes`` signature is a
        documentation contract rather than a runtime constraint here.

        Args:
            request: The incoming request. Unused (the redirect target
                is configuration-driven, not request-derived) but kept
                in the signature to match the base class.
            openapi_schema: The fully-generated OpenAPI schema. Unused
                because we never render OpenAPI HTML from this plugin.

        Returns:
            A :class:`Redirect` Response pointing at
            :attr:`Settings.ui_path` with status ``302``. Typed as
            ``bytes`` to match the upstream contract — see the
            class-level note above.
        """
        return Redirect(path=settings.ui_path, status_code=302, media_type=self.media_type)


def build_spa_route_handler() -> Router:
    """Build the static-files router that serves the React SPA.

    Returns the :class:`~litestar.router.Router` that serves the entire
    bundled output directory ``src/fusionserve/web/dist`` (containing
    ``index.html`` and the ``assets/`` sub-directory with hashed JS/CSS
    chunks) at :attr:`Settings.ui_path`.

    Key configuration:

    - ``html_mode=True`` makes Litestar serve ``index.html`` for the
      mount root and as a fallback for unmatched paths, which gives
      the SPA's client-side router a no-broken-deep-link guarantee
      (belt-and-braces alongside the SPA's existing hash routing).
    - ``opt={"exclude_from_auth": True}`` opts the entire router out
      of the auth middleware, which honours
      :attr:`~litestar.middleware.AbstractAuthenticationMiddleware.exclude_opt_key`
      (set to ``"exclude_from_auth"`` by Litestar's default). Without
      this, every static asset would trigger an unnecessary
      authentication round-trip.

    The router serves the chunks too — Vite is configured (in
    ``ui/vite.config.ts``) to emit relative asset URLs (``./assets/...``
    in ``index.html``), so the browser resolves them against the served
    SPA URL (``<ui_path>/assets/<hash>.<ext>``) and the same router
    maps that to ``<bundle_dir>/assets/<hash>.<ext>`` on disk. No
    separate asset prefix configuration is required, and relocating
    the SPA is a one-setting change (override :attr:`Settings.ui_path`).

    The ``settings.ui_enabled`` gate is the caller's responsibility —
    this function unconditionally builds and returns the router.

    Returns:
        A :class:`Router` ready to be added to
        :class:`litestar.Litestar`'s ``route_handlers`` list.
    """
    return create_static_files_router(
        path=settings.ui_path,
        directories=[_BUNDLE_DIR],
        html_mode=True,
        name="ui",
        opt={"exclude_from_auth": True},
    )


__all__ = ("RedirectRenderPlugin", "build_spa_route_handler")
