"""UI integration for FusionServe.

This module wires the Angular SPA built under ``ui/`` into the Litestar
application using Litestar's first-party static-files router. Two
artefacts are exported:

- :class:`RedirectRenderPlugin` — a custom
  :class:`~litestar.openapi.plugins.OpenAPIRenderPlugin` registered as
  the default plugin on the OpenAPI router. The upstream OpenAPI plugin
  auto-mounts the default plugin at the configured router root, so
  ``GET <base_path>/`` returns a 302 redirect to :attr:`Settings.ui_path`
  (default ``/api/-/``) where the SPA is mounted. Sibling render plugins
  (``SwaggerRenderPlugin``, ``ScalarRenderPlugin``) coexist normally at
  ``<base_path>/swagger`` and ``<base_path>/scalar``.
- :func:`build_spa_route_handler` — returns two route handlers serving the
  SPA under :attr:`Settings.ui_path`:

  * an **assets** static-files router at ``<ui_path>assets`` serving the
    Angular browser bundle (hashed JS/CSS chunks, ``index.html`` and any
    media / embedded viewer assets) from ``src/fusionserve/web/dist/assets``
    (shipped inside the Python wheel). Angular's application builder is
    configured (``ui/angular.json`` ``outputPath.browser = "assets"``) to
    emit its whole browser bundle under this single ``assets/`` prefix, so
    the disjoint-prefix design that keeps the static router and the index
    fallback from colliding is preserved.
  * a **base-href-injecting index handler** that serves ``index.html`` for
    the mount root and as the deep-link fallback for any other path under
    the mount. The SPA uses browser-history (path) routing, so it injects
    ``<base href="<ui_path>assets/">`` into the served HTML; Angular's
    *relative* asset URLs (``main-<hash>.js`` …) then resolve to
    ``<ui_path>assets/...`` regardless of the current deep route. The
    Angular router base is derived one level up (``<ui_path>``) from the
    document base href via ``APP_BASE_HREF`` (see ``ui/src/app/app.config.ts``).
    The SPA therefore stays location-independent — relocating it is a single
    change to :attr:`Settings.ui_path` with no JS rebuild.

The router carries ``opt={"exclude_from_auth": True}`` so the
authentication middleware (which honours that key via
:attr:`~litestar.middleware.AbstractAuthenticationMiddleware.exclude_opt_key`)
skips static assets without needing routes added to its URL-pattern
exclude list. The dev workflow is fully out-of-process: developers run
``pnpm run dev`` in ``ui/`` and the Angular dev server proxies ``/api``
to the Litestar backend. The Python side only serves the prebuilt SPA
from ``src/fusionserve/web/dist`` (regenerated by ``pnpm run build``).

Path / routing notes:

- The default :attr:`Settings.ui_path` (``/api/-/``) lives **inside**
  :attr:`Settings.base_path`. Litestar's path-converter matcher
  ``{path:str}`` matches a single segment without slashes, so the
  OpenAPI router's auto-registered ``<base_path>/{path:str}`` not-found
  handler does **not** shadow multi-segment paths like ``/api/-/...``;
  the SPA handlers' more-specific prefix wins.
- The index handler is registered for the mount root and a multi-segment
  ``{path:path}`` catch-all so client-side deep links (e.g.
  ``/api/-/data/users``) reload to ``index.html``. The more-specific
  ``<ui_path>assets`` static router wins for asset requests.
- The trailing-slash form ``<ui_path>`` (e.g. ``/api/-/``) is canonical.
  The slashless ``<base_path>/-`` form is reachable by the OpenAPI
  not-found handler and will 404 — document the trailing slash to users
  (the ``/api/`` redirect emits it correctly).
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from functools import lru_cache
from pathlib import Path
from typing import Any

from litestar import Response, get
from litestar.connection import Request
from litestar.enums import MediaType, OpenAPIMediaType
from litestar.exceptions import NotFoundException
from litestar.handlers import HTTPRouteHandler
from litestar.openapi.plugins import OpenAPIRenderPlugin
from litestar.response import Redirect
from litestar.router import Router
from litestar.static_files import create_static_files_router

from .config import settings

#: Repository / package layout, derived from this file's location.
#: Layout assumed: ``<repo>/src/fusionserve/ui.py``. Used to resolve
#: the bundled ``web/dist`` output directory.
_PACKAGE_DIR: Path = Path(__file__).resolve().parent

#: Where the production Angular build emits its output. Co-located with the
#: Python package so the wheel ships the built SPA without extra
#: packaging configuration.
_BUNDLE_DIR: Path = _PACKAGE_DIR / "web" / "dist"

#: Angular emits its whole browser bundle (JS/CSS, ``index.html``, media)
#: under an ``assets`` subdirectory of the build output (configured via
#: ``outputPath.browser`` in ``ui/angular.json``). Serving everything from a
#: single disjoint ``assets/`` prefix keeps the static-files router from
#: colliding with the ``{path:path}`` index fallback.
_ASSETS_DIR: Path = _BUNDLE_DIR / "assets"


class RedirectRenderPlugin(OpenAPIRenderPlugin):
    """OpenAPI render plugin that redirects to the Angular SPA.

    Registered as the first entry of
    :attr:`~litestar.openapi.OpenAPIConfig.render_plugins`, this plugin
    becomes the *default* plugin. Litestar's OpenAPI router auto-mounts
    the default plugin's handler at the router root (``settings.base_path``
    in our setup), so ``GET /api/`` returns a 302 redirect to
    :attr:`Settings.ui_path` — where the SPA static-files router serves
    ``index.html``. Users hitting the canonical API base URL land in the
    UI without having to know the SPA path.

    The plugin departs from the sibling render plugins
    (``JsonRenderPlugin``, ``SwaggerRenderPlugin``, …) in one important
    way: :meth:`render` returns a :class:`~litestar.response.Redirect`
    Response rather than ``bytes``. Litestar handles ``Response`` returns
    from handlers regardless of the declared return annotation, so the
    302 is served directly; the upstream ``-> bytes`` signature is kept
    only for API parity with the rest of the render-plugin family.
    """

    def __init__(
        self,
        *,
        path: str | Sequence[str] = "",
        media_type: MediaType | OpenAPIMediaType = MediaType.TEXT,
        **kwargs: Any,
    ) -> None:
        """Initialise the redirect plugin.

        Args:
            path: Path (relative to the OpenAPI router root) at which the
                redirect handler is registered. Defaults to ``""`` so the
                handler binds to the router root itself — the upstream
                OpenAPI plugin additionally promotes the default plugin's
                handler to ``"/"``, which together means ``/api`` and
                ``/api/`` both redirect.
            media_type: Required by the
                :class:`OpenAPIRenderPlugin` base class but practically
                ignored: the :class:`Redirect` Response sets its own
                ``Location`` header and ``302`` status independently of
                the declared media type.
            **kwargs: Forwarded to the base class for forward-compat with
                future :class:`OpenAPIRenderPlugin` parameters.
        """
        super().__init__(path=path, media_type=media_type, **kwargs)

    def render(self, request: Request, openapi_schema: dict[str, Any]) -> bytes:
        """Return a 302 redirect to :attr:`Settings.ui_path`.

        The return type annotation is ``bytes`` for parity with the
        :class:`OpenAPIRenderPlugin` contract, but the actual return
        value is a :class:`~litestar.response.Redirect` Response.
        Litestar's response cycle accepts any ``Response`` instance from
        a handler return — it short-circuits serialization and sends the
        response as-is — so the upstream ``-> bytes`` signature is a
        documentation contract rather than a runtime constraint here.

        Args:
            request: The incoming request. Unused (the redirect target
                is configuration-driven, not request-derived) but kept
                in the signature to match the base class.
            openapi_schema: The fully-generated OpenAPI schema. Unused
                because we never render OpenAPI HTML from this plugin.

        Returns:
            A :class:`Redirect` Response pointing at
            :attr:`Settings.ui_path` with status ``302``. Typed as
            ``bytes`` to match the upstream contract — see the
            class-level note above.
        """
        return Redirect(path=settings.ui_path, status_code=302, media_type=self.media_type)


@lru_cache(maxsize=1)
def _render_index() -> str:
    """Return ``index.html`` with ``<base href>`` set to ``<ui_path>assets/``.

    The SPA uses browser-history routing, so the served HTML must declare a
    ``<base href>`` matching where the hashed bundle lives (Angular emits
    relative ``main-<hash>.js`` URLs that resolve against it). Angular writes
    its whole browser bundle — including ``index.html`` — under the build's
    ``assets/`` subdirectory, so the base href points at
    ``<ui_path>assets/``. The on-disk file ships a placeholder
    ``<base href="/">`` (the dev default); here it is rewritten. The Angular
    router base is derived one level up (``<ui_path>``) at runtime via
    ``APP_BASE_HREF`` (see ``ui/src/app/app.config.ts``).

    The result is cached for the process lifetime: the served bundle is only
    (re)built in CI, never at runtime, and ``settings.ui_path`` is fixed at
    startup, so the rendered HTML is immutable while the process runs.
    ``lru_cache`` does not cache exceptions, so a call before the SPA is built
    raises without poisoning the cache and recovers once the bundle exists.

    Returns:
        The rewritten ``index.html`` markup.

    Raises:
        NotFoundException: If the SPA has not been built (``index.html``
            missing under the bundle's ``assets`` directory).
    """
    index_path = _ASSETS_DIR / "index.html"
    try:
        html = index_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise NotFoundException("SPA index.html not found; build the UI first") from exc

    base_tag = f'<base href="{settings.ui_path}assets/" />'
    if "<base" in html:
        return re.sub(r"<base\b href=[^>]*>", base_tag, html, count=1)
    return html.replace("<head>", f"<head>\n    {base_tag}", 1)


def _build_index_handler() -> HTTPRouteHandler:
    """Build the GET handler that serves the SPA shell (with injected base href).

    Registered for the mount root and a multi-segment ``{path:path}``
    catch-all so client-side deep links reload to ``index.html``. Asset
    requests are served by the more-specific assets router instead.
    """

    @get(
        [settings.ui_path, f"{settings.ui_path}{{path:path}}"],
        name="ui-index",
        opt={"exclude_from_auth": True},
        media_type=MediaType.HTML,
        include_in_schema=False,
        sync_to_thread=False,
    )
    def serve_spa_index(path: str = "") -> Response[str]:
        return Response(_render_index(), media_type=MediaType.HTML)

    return serve_spa_index


def build_spa_route_handler() -> Sequence[Router | HTTPRouteHandler]:
    """Build the route handlers that serve the Angular SPA.

    Returns two handlers, both opted out of the auth middleware via
    ``opt={"exclude_from_auth": True}`` (honoured through
    :attr:`~litestar.middleware.AbstractAuthenticationMiddleware.exclude_opt_key`):

    - an **assets** static-files router at ``<ui_path>assets`` serving the
      Angular browser bundle from ``<bundle_dir>/assets`` (``html_mode=False``
      — only real files; traversal-protected by Litestar);
    - a **base-href-injecting index handler** (see :func:`_build_index_handler`)
      serving ``index.html`` for the mount root and as the deep-link fallback.

    Splitting the two (rather than a single ``html_mode=True`` router) is what
    lets us rewrite ``<base href>`` in the served HTML while still serving the
    chunks verbatim — so the browser-history SPA resolves relative asset URLs
    correctly at any depth and the mount stays relocatable via
    :attr:`Settings.ui_path`.

    The ``settings.ui_enabled`` gate is the caller's responsibility.

    Returns:
        A sequence of handlers ready to be added to
        :class:`litestar.Litestar`'s ``route_handlers`` list.
    """
    assets_router = create_static_files_router(
        path=f"{settings.ui_path.rstrip('/')}/assets",
        directories=[_ASSETS_DIR],
        html_mode=False,
        name="ui-assets",
        opt={"exclude_from_auth": True},
    )
    return (assets_router, _build_index_handler())


__all__ = ("RedirectRenderPlugin", "build_spa_route_handler")
