"""Storage backend abstraction for the file-uploads feature.

A :class:`StorageBackend` is the narrow contract every concrete storage
implementation must satisfy. The bundled backends are
:class:`fusionserve.storage.filesystem.FilesystemBackend` and
:class:`fusionserve.storage.s3.S3Backend`; third-party backends plug in via
the dotted-import-path syntax accepted by
:func:`fusionserve.storage.load_backend`.

The contract is intentionally small: ``save`` / ``open`` / ``delete`` /
``stat`` / ``presigned_url``. Multi-file uploads are handled at the
controller layer by calling ``save`` once per file. Resumable uploads are
deliberately out of scope.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from contextlib import AbstractAsyncContextManager
from dataclasses import dataclass
from typing import Protocol, runtime_checkable


@dataclass(frozen=True)
class StorageObject:
    """Metadata returned by storage backends after a write/stat.

    Attributes:
        key: The backend-relative key under which the object lives.
            Server-generated, never client-controlled.
        size_bytes: The verified, post-write size of the object in bytes.
        content_type: The MIME type declared at save time.
        etag: Backend-specific opaque integrity tag. ``None`` when the
            backend does not expose one (filesystem) or when ``stat`` is
            called and the backend does not surface it cheaply.
    """

    key: str
    size_bytes: int
    content_type: str
    etag: str | None = None


@runtime_checkable
class StorageBackend(Protocol):
    """Async storage backend protocol.

    Implementations must be safe to share across the application
    lifetime (the configured backend is instantiated once at startup;
    see :func:`fusionserve.storage.get_storage`). Methods that touch the
    network must use ``async`` I/O.
    """

    async def save(
        self,
        key: str,
        stream: AsyncIterator[bytes],
        *,
        content_type: str,
        declared_size: int | None,
    ) -> StorageObject:
        """Persist a byte stream under ``key``.

        Args:
            key: The destination key (server-generated by the controller).
            stream: An async iterator yielding the file's bytes.
            content_type: The MIME type advertised by the upload.
            declared_size: The ``Content-Length`` declared by the client,
                when available; backends MAY use this for optimisation
                (e.g. choosing single-PUT vs. multipart) but MUST NOT
                trust it as a security bound — the controller enforces
                the size cap independently while streaming.

        Returns:
            A :class:`StorageObject` describing the persisted object.
        """
        ...

    def open(self, key: str) -> AbstractAsyncContextManager[AsyncIterator[bytes]]:
        """Open ``key`` for streaming download.

        Implementations return an async context manager whose body
        yields an async iterator of byte chunks. Callers MUST iterate
        within the ``async with`` block; the chunks are no longer valid
        outside it.
        """
        ...

    async def delete(self, key: str) -> None:
        """Remove ``key`` from the backend.

        Implementations are idempotent: deleting a non-existent key
        succeeds silently. Any other error is raised.
        """
        ...

    async def stat(self, key: str) -> StorageObject:
        """Return metadata for ``key``.

        Raises:
            FileNotFoundError: If the key does not exist.
        """
        ...

    async def presigned_url(self, key: str, *, expires_in: int) -> str | None:
        """Return a presigned GET URL for ``key`` or ``None``.

        Backends that cannot offer presigned URLs (e.g. local filesystem)
        return ``None``; the controller then falls back to streaming the
        bytes through the application.

        Args:
            key: The object key.
            expires_in: Lifetime of the URL in seconds.

        Returns:
            A presigned URL, or ``None`` if the backend does not support
            presigning.
        """
        ...
