"""Storage backend abstraction for the file-uploads feature.

A :class:`StorageBackend` is the narrow contract every concrete storage
implementation must satisfy. The bundled backend is
:class:`fusionserve.storage.s3.S3Backend`; an
:class:`fusionserve.storage.azure.AzureBlobBackend` placeholder reserves
the ``"azure"`` selector, and third-party backends plug in via the
dotted-import-path syntax accepted by
:func:`fusionserve.storage.load_backend`.

The contract is intentionally small and byte-free: FusionServe never
streams object bytes through itself in the normal flow. Instead it hands
the client a **presigned upload URL** (``generate_upload_url``) and a
**presigned download URL** (``generate_download_url``); the client talks
to the object store directly. ``stat`` verifies an object after upload,
``delete`` removes it, and ``object_origin`` exposes the canonical
``scheme://host`` the backend's presigned URLs point at so the optional
HTTP proxy (see :mod:`fusionserve.files.proxy`) can relay to it.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass
from typing import Protocol, runtime_checkable


@dataclass(frozen=True)
class StorageObject:
    """Metadata returned by ``stat`` after an object has been uploaded.

    Attributes:
        key: The backend-relative key under which the object lives.
            Server-generated, never client-controlled.
        size_bytes: The verified size of the object in bytes.
        content_type: The MIME type stored with the object.
        etag: Backend-specific opaque integrity tag, or ``None`` when the
            backend does not surface one.
    """

    key: str
    size_bytes: int
    content_type: str
    etag: str | None = None


@dataclass(frozen=True)
class UploadTicket:
    """A time-limited authorization for a client to upload one object.

    Attributes:
        url: The presigned URL the client must send the bytes to.
        method: The HTTP method the client must use (``"PUT"`` for S3).
        headers: Request headers the client MUST send for the presigned
            signature to validate (e.g. ``Content-Type``).
        expires_at: When the presigned URL stops being valid.
    """

    url: str
    method: str
    headers: dict[str, str]
    expires_at: datetime.datetime


@runtime_checkable
class StorageBackend(Protocol):
    """Async storage backend protocol.

    Implementations must be safe to share across the application
    lifetime (the configured backend is instantiated once at startup;
    see :func:`fusionserve.storage.get_storage`). Methods that touch the
    network must use ``async`` I/O.
    """

    async def generate_upload_url(self, key: str, *, content_type: str, expires_in: int) -> UploadTicket:
        """Return a presigned URL the client can upload ``key`` to.

        Args:
            key: The destination key (server-generated by the controller).
            content_type: The MIME type the object will be stored with.
                Backends MAY bind this into the signature, in which case
                the client must send a matching ``Content-Type`` header.
            expires_in: Lifetime of the presigned URL in seconds.

        Returns:
            An :class:`UploadTicket` describing the URL, method and
            required headers.
        """
        ...

    async def generate_download_url(self, key: str, *, expires_in: int) -> str:
        """Return a presigned GET URL for ``key``.

        Args:
            key: The object key.
            expires_in: Lifetime of the URL in seconds.

        Returns:
            A presigned URL the client can GET the object from.
        """
        ...

    async def stat(self, key: str) -> StorageObject:
        """Return metadata for ``key``.

        Raises:
            FileNotFoundError: If the key does not exist.
        """
        ...

    async def delete(self, key: str) -> None:
        """Remove ``key`` from the backend.

        Implementations are idempotent: deleting a non-existent key
        succeeds silently. Any other error is raised.
        """
        ...

    async def object_origin(self) -> str:
        """Return the canonical ``scheme://host`` presigned URLs point at.

        Used by the optional HTTP proxy to reconstruct the real object-
        store URL from a request whose origin has been rewritten to
        FusionServe. Implementations MUST return the exact origin their
        presigned URLs use (host included in the signature), so a relayed
        request validates against the object store.
        """
        ...
