import type { ReactNode } from "react";
import { Link } from "@tanstack/react-router";

import { ThemeToggle } from "./ThemeToggle";
import { UserBadge } from "./UserBadge";

interface NavItem {
  to: string;
  label: string;
  description: string;
}

const NAV: readonly NavItem[] = [
  { to: "/", label: "Overview", description: "Welcome page" },
  { to: "/openapi", label: "OpenAPI", description: "Interactive API reference" },
  { to: "/graphql", label: "GraphQL", description: "GraphiQL IDE" },
];

// Short tagline shown beside the wordmark (separated by a thin divider),
// echoing the dashboard-screenshot brand treatment.
const TAGLINE = "PostgreSQL API Surface";

interface AppLayoutProps {
  children: ReactNode;
}

export function AppLayout({ children }: AppLayoutProps) {
  return (
    <div className="flex min-h-full flex-col">
      <header className="sticky top-0 z-10 border-b border-zinc-200 bg-white/90 shadow-sm backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/90">
        <div className="flex items-center gap-6 px-6 py-3.5 lg:px-8">
          <Link to="/" className="flex items-center gap-3 whitespace-nowrap">
            <span className="text-lg font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
              FusionServe
            </span>
            <span
              aria-hidden="true"
              className="h-5 w-px bg-zinc-300 dark:bg-zinc-700"
            />
            <span className="hidden text-sm font-medium text-zinc-500 sm:inline dark:text-zinc-400">
              {TAGLINE}
            </span>
          </Link>
          <nav className="flex items-center gap-1 text-sm font-medium">
            {NAV.map((item) => (
              <Link
                key={item.to}
                to={item.to}
                title={item.description}
                className="relative px-3 py-2 text-zinc-600 transition-colors after:absolute after:inset-x-3 after:-bottom-px after:h-0.5 after:rounded-full after:bg-transparent after:transition-colors hover:text-zinc-900 data-[active]:text-blue-600 data-[active]:after:bg-blue-600 dark:text-zinc-400 dark:hover:text-zinc-100 dark:data-[active]:text-blue-400 dark:data-[active]:after:bg-blue-400"
                activeProps={{ "data-active": "true" }}
                activeOptions={{ exact: item.to === "/" }}
              >
                {item.label}
              </Link>
            ))}
          </nav>
          <div className="ml-auto flex items-center gap-3">
            <ThemeToggle />
            <UserBadge />
          </div>
        </div>
      </header>
      <main className="w-full flex-1 px-6 py-8 lg:px-8">{children}</main>
      <footer className="border-t border-zinc-200 bg-white/80 py-4 text-center text-xs text-zinc-500 dark:border-zinc-800 dark:bg-zinc-900/80 dark:text-zinc-400">
        FusionServe — REST + GraphQL surface generated by PostgreSQL introspection.
      </footer>
    </div>
  );
}
