import type { ReactNode } from "react";
import { Link } from "@tanstack/react-router";

interface NavItem {
  to: string;
  label: string;
  description: string;
}

const NAV: readonly NavItem[] = [
  { to: "/", label: "Overview", description: "Welcome page" },
  { to: "/openapi", label: "OpenAPI", description: "Interactive API reference" },
  { to: "/graphql", label: "GraphQL", description: "GraphiQL IDE" },
];

interface AppLayoutProps {
  children: ReactNode;
}

export function AppLayout({ children }: AppLayoutProps) {
  return (
    <div className="flex min-h-full flex-col">
      <header className="border-b border-zinc-200 bg-white/80 backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/80">
        <div className="mx-auto flex max-w-6xl items-center gap-6 px-6 py-4">
          <Link
            to="/"
            className="font-semibold tracking-tight text-zinc-900 hover:text-zinc-700 dark:text-zinc-50 dark:hover:text-zinc-200"
          >
            FusionServe
          </Link>
          <nav className="flex items-center gap-1 text-sm">
            {NAV.map((item) => (
              <Link
                key={item.to}
                to={item.to}
                title={item.description}
                className="rounded-md px-3 py-1.5 text-zinc-600 transition-colors hover:bg-zinc-100 hover:text-zinc-900 data-[active]:bg-zinc-900 data-[active]:text-zinc-50 dark:text-zinc-400 dark:hover:bg-zinc-800 dark:hover:text-zinc-100 dark:data-[active]:bg-zinc-50 dark:data-[active]:text-zinc-900"
                activeProps={{ "data-active": "true" }}
              >
                {item.label}
              </Link>
            ))}
          </nav>
        </div>
      </header>
      <main className="mx-auto w-full max-w-6xl flex-1 px-6 py-8">{children}</main>
      <footer className="border-t border-zinc-200 bg-white/80 py-4 text-center text-xs text-zinc-500 dark:border-zinc-800 dark:bg-zinc-900/80 dark:text-zinc-400">
        FusionServe — REST + GraphQL surface generated by PostgreSQL introspection.
      </footer>
    </div>
  );
}
