import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

import { ThemeToggle } from './theme-toggle';
import { UserBadge } from './user-badge';

interface NavItem {
  path: string;
  label: string;
  description: string;
  exact: boolean;
}

const NAV: readonly NavItem[] = [
  { path: '/', label: 'Overview', description: 'Welcome page', exact: true },
  { path: '/data', label: 'Data', description: 'Browse and edit table data', exact: false },
  { path: '/openapi', label: 'OpenAPI', description: 'Interactive API reference', exact: false },
  { path: '/graphql', label: 'GraphQL', description: 'GraphQL IDE', exact: false },
];

/**
 * Application shell: a top nav bar (wordmark + tagline, primary navigation,
 * theme toggle and user badge), a scrollable main content area rendering the
 * routed view, and a footer.
 */
@Component({
  selector: 'app-layout',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, RouterLinkActive, RouterOutlet, ThemeToggle, UserBadge],
  template: `
    <div class="flex h-full flex-col overflow-hidden">
      <header
        class="z-10 shrink-0 border-b border-zinc-200 bg-white/90 shadow-sm backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/90"
      >
        <div class="flex items-center gap-6 px-6 py-3.5 lg:px-8">
          <a routerLink="/" class="flex items-center gap-3 whitespace-nowrap">
            <span class="text-lg font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
              FusionServe
            </span>
            <span aria-hidden="true" class="h-5 w-px bg-zinc-300 dark:bg-zinc-700"></span>
            <span class="hidden text-sm font-medium text-zinc-500 sm:inline dark:text-zinc-400">
              {{ tagline }}
            </span>
          </a>
          <nav class="flex items-center gap-1 text-sm font-medium">
            @for (item of nav; track item.path) {
              <a
                [routerLink]="item.path"
                [routerLinkActive]="'text-blue-600 after:bg-blue-600 dark:text-blue-400 dark:after:bg-blue-400'"
                [routerLinkActiveOptions]="{ exact: item.exact }"
                [title]="item.description"
                class="relative px-3 py-2 text-zinc-600 transition-colors after:absolute after:inset-x-3 after:-bottom-px after:h-0.5 after:rounded-full after:bg-transparent after:transition-colors hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100"
              >
                {{ item.label }}
              </a>
            }
          </nav>
          <div class="ml-auto flex items-center gap-3">
            <app-theme-toggle />
            <app-user-badge />
          </div>
        </div>
      </header>
      <main class="min-h-0 w-full flex-1 overflow-y-auto px-6 py-8 lg:px-8">
        <router-outlet />
      </main>
      <footer
        class="shrink-0 border-t border-zinc-200 bg-white/80 py-4 text-center text-xs text-zinc-500 dark:border-zinc-800 dark:bg-zinc-900/80 dark:text-zinc-400"
      >
        FusionServe — REST + GraphQL surface generated by PostgreSQL introspection.
      </footer>
    </div>
  `,
})
export class AppLayout {
  // Short tagline shown beside the wordmark (separated by a thin divider).
  protected readonly tagline = 'PostgreSQL API Surface';
  protected readonly nav = NAV;
}
